export const modules = [
  {
    title: "Queue",
    image: "/icons/ticket.png",
    alt: "",
    target: "/menu/queue",
    active: true,
  },
  {
    title: "Real Property",
    image: "/icons/home.png",
    alt: "",
    target: "/menu/rpt",
    active: true,
  },
  {
    title: "Business Permit",
    image: "/icons/briefcase.png",
    alt: "",
    target: "/menu/bpls",
    active: true,
  },
  {
    title: "Building Construction Permit",
    image: "/icons/helmet.png",
    alt: "",
    target: "/menu/obo",
    active: true,
  },
  {
    title: "Vehicle Registration",
    image: "/icons/taxi.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Market Rental",
    image: "/icons/bag.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Water",
    image: "/icons/water.png",
    alt: "",
    target: "/menu/water",
    active: false,
  },
  {
    title: "Cedula",
    image: "/icons/user.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Police Clearance",
    image: "/icons/badge.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Health Permit",
    image: "/icons/health.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Ordinance Violations",
    image: "/icons/violation.png",
    alt: "",
    target: "",
    active: false,
  },
  {
    title: "Work Permit",
    image: "/icons/permit.png",
    alt: "",
    target: "",
    active: false,
  },
];
