export const modules = [
  {
    title: "Cedula",
    image: "",
    alt: "Cedula icon",
    target: "/Cedula",
    height: 100,
    width: 100,
  },
  {
    title: "Real Property",
    image: "/images/icons/home.png",
    alt: "Real Property icon",
    target: "/Real Property",
    height: 80,
    width: 80,
  },
  {
    title: "Business Permit",
    image: "/images/icons/briefcase.png",
    alt: "Business Permit icon",
    target: "/Business Permit",
    height: 100,
    width: 100,
  },
  {
    title: "Building Construction Permit",
    image: "/images/icons/helmet.png",
    alt: "Building Construction Permit icon",
    target: "",
    height: 100,
    width: 100,
  },
  {
    title: "Vehicle Registration",
    image: "/images/icons/taxi.png",
    alt: "Vehicle Registration icon",
    target: "",
    height: 80,
    width: 80,
  },
  {
    title: "Market Rental",
    image: "/images/icons/bag.png",
    alt: "Market Rental icon",
    target: "",
    height: 80,
    width: 80,
  },
  {
    title: "Water",
    image: "/images/icons/water.png",
    alt: "Water icon",
    target: "",
    height: 80,
    width: 80,
  },
  {
    title: "Queue",
    image: "/images/icons/ticket.png",
    alt: "Queue icon",
    target: "/queue",
    height: 100,
    width: 100,
  },
  {
    title: "Police Clearance",
    image: "",
    alt: "Police Clearance icon",
    target: "",
    height: 100,
    width: 100,
  },
  {
    title: "Health Permit",
    image: "",
    alt: "Health Permit",
    target: "",
    height: 100,
    width: 100,
  },
  {
    title: "Ordinance Violations",
    image: "",
    alt: "Ordinance Violations icon",
    target: "",
    height: 100,
    width: 100,
  },
  {
    title: "Work Permit",
    image: "",
    alt: "Work Permit icon",
    target: "",
    height: 100,
    width: 100,
  },
];
