export const modules = [
  {
    title: "Queue",
    image: "/icons/ticket.png",
    alt: "",
    target: "/menu/queue",
    height: 70,
    width: 70,
  },
  {
    title: "Real Property",
    image: "/icons/home.png",
    alt: "",
    target: "/menu/property",
    height: 70,
    width: 70,
  },
  {
    title: "Business Permit",
    image: "/icons/briefcase.png",
    alt: "",
    target: "/menu/bpls",
    height: 70,
    width: 70,
  },
  {
    title: "Building Construction Permit",
    image: "/icons/helmet.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Vehicle Registration",
    image: "/icons/taxi.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Market Rental",
    image: "/icons/bag.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Water",
    image: "/icons/water.png",
    alt: "",
    target: "/menu/water",
    height: 70,
    width: 70,
  },
  {
    title: "Cedula",
    image: "/icons/user.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Police Clearance",
    image: "/icons/badge.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Health Permit",
    image: "/icons/health.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Ordinance Violations",
    image: "/icons/violation.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
  {
    title: "Work Permit",
    image: "/icons/permit.png",
    alt: "",
    target: "",
    height: 70,
    width: 70,
  },
];
