const queueItems = [
  {
    objid: {},
    title: "Cedula",
    type: {},
    modalcontent: {
      queuetitle: "Cedula",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 101,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Water",
    type: {},
    modalcontent: {
      queuetitle: "Water",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 99,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Construction Permit",
    type: {},
    modalcontent: {
      queuetitle: "Construction Permit",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 12,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Ordinance Violations",
    type: {},
    modalcontent: {
      queuetitle: "Ordinance Violations",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 69,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Vehicle Registration",
    type: {},
    modalcontent: {
      queuetitle: "Vehicle Registration",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 14,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Health Permit",
    type: {},
    modalcontent: {
      queuetitle: "Health Permit",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 13,
      textbutton: "Print",
    },
  },
  {
    objid: {},
    title: "Work Permit",
    type: {},
    modalcontent: {
      queuetitle: "Work Permit",
      image: "/images/qr.png",
      imageheight: 200,
      imagewidth: 200,
      subtitle: "Present this qr code to the cashier",
      title: "Queue No.",
      number: 76,
      textbutton: "Print",
    },
  },
];

export default queueItems;
